# conf/spark-defaults.conf

spark.master                     spark://spark-master:7077
spark.sql.shuffle.partitions     8
spark.executor.memory            512m
spark.executor.cores             1
spark.driver.memory              512m

# UI 히스토리 보존
spark.eventLog.enabled           true
spark.eventLog.dir               /tmp/spark-events